class NODE_MT_add:
    _dyn_owner_apply: any
    _dyn_ui_initialize: any
    append: any
    as_pointer: any
    bl_label: any
    bl_rna: any
    bl_rna_get_subclass: any
    bl_rna_get_subclass_py: any
    bl_space_type: any
    bl_translation_context: any
    draw: any
    draw_collapsible: any
    draw_preset: any
    driver_add: any
    driver_remove: any
    get: any
    id_data: any
    id_properties_clear: any
    id_properties_ensure: any
    id_properties_ui: any
    is_extended: any
    is_property_hidden: any
    is_property_overridable_library: any
    is_property_readonly: any
    is_property_set: any
    items: any
    keyframe_delete: any
    keyframe_insert: any
    keys: any
    path_from_id: any
    path_menu: any
    path_resolve: any
    pop: any
    prepend: any
    property_overridable_library_set: any
    property_unset: any
    remove: any
    type_recast: any
    values: any