# https://docs.blender.org/api/current/bpy.app.html

autoexec_fail: any
autoexec_fail_message: any
autoexec_fail_quiet: any
binary_path: any
debug: bool
debug_depsgraph: bool
debug_depsgraph_build: bool
debug_depsgraph_eval: bool
debug_depsgraph_pretty: bool
debug_depsgraph_tag: bool
debug_depsgraph_time: bool
debug_events: bool
debug_ffmpeg: bool
debug_freestyle: bool
debug_handlers: bool
debug_io: bool
debug_python: bool
debug_simdata: bool
debug_value: int
debug_wm: bool
driver_namespace: any
render_icon_size: any
render_preview_size: any
tempdir: str
use_event_simulate: bool
use_userpref_skip_save_on_exit: bool
background: bool
factory_startup: bool
build_branch: bool
build_cflags: any
build_commit_date: any
build_commit_time: any
build_cxxflags: any
build_date: any
build_hash: any
build_linkflags: any
build_platform: any
build_system: any
build_time: any
build_type: any
build_commit_timestamp: any
version_char: any
version_cycle: any
version_string: any
version: any
version_file: any
alembic: any
build_options: any
ffmpeg: any
ocio: any
oiio: any
opensubdiv: any
openvdb: any
sdl: any
usd: any

def is_job_running(job_type: str) -> bool:
    pass